<script type="text/javascript" src="${resources}/js/jquery-3.3.1.min.js"></script>
<script type="text/javascript" src="${resources}/js/bootstrap.min.js"></script>
<script type="text/javascript" src="${resources}/js/jquery.nice-select.min.js"></script>
<script type="text/javascript" src="${resources}/js/jquery-ui.min.js"></script>
<script type="text/javascript" src="${resources}/js/jquery.nicescroll.min.js"></script>
<script type="text/javascript" src="${resources}/js/jquery.barfiller.js"></script>
<script type="text/javascript" src="${resources}/js/jquery.magnific-popup.min.js"></script>
<script type="text/javascript" src="${resources}/js/jquery.slicknav.js"></script>
<script type="text/javascript" src="${resources}/js/owl.carousel.min.js"></script>
<script type="text/javascript" src="${resources}/js/main.js"></script> 